version: '3.7'

services:
  api:
    container_name: api
    image: api-api
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ["sh", "docker-entrypoint.sh"]
    command: ["rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    env_file: .env
    volumes:
      - "./:/opt/app"
    depends_on:
      - db

  db:
    image: postgres:14.6
    ports:
      - "5432:5432"
    env_file: .env
